# Generated by Django 4.0.4 on 2022-12-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='Customer',
            new_name='customer',
        ),
    ]
